name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - uses: taiki-e/install-action@just

      - name: Lint
        run: just lint

      - name: Format code
        run: just check-format

      - name: Check documentation is up to date
        run: just check-docs
