name: Tests

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Show Forge version
        run: forge --version
      - name: Install Solidity compiler
        run: sudo ./scripts/ci/install-solc.sh
      - name: Run tests
        run: cargo test --lib
  run-fuzz-tests:
    name: Run fuzz tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install Solidity compiler
        run: sudo ./scripts/ci/install-solc.sh
      - name: Run tests
        run: cargo test --lib -- state::fuzz --show-output
        env:
          FUZZ: 1
          NUM_TESTS: 200
  run-smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run tests
        run: cargo test --test integration_tests
